#!/bin/bash

image=/home/vincent/Pictures/lockscreen/cat_lock.png
lock_cmd="swaylock -f -i $image"

/usr/bin/swayidle -w \
  timeout 600  "$lock_cmd" \
  timeout 800 "swaymsg 'output * dpms off'" \
  resume "swaymsg 'output * dpms on'" \
  timeout 1800 "systemctl suspend" \
  before-sleep "$lock_cmd" \
  lock "$lock_cmd"
