monitor.alsa.rules = [
  {
    matches = [
      {
        node.nick = "HDMI / DisplayPort 2 Output"
      }
      {
        node.nick = "HDMI / DisplayPort 3 Output"
      }
      {
        node.name = "alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y7RN4G5265215E-00.HiFi__Mic2__source"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
