#!/bin/bash

set -eo pipefail

date=$(date -Is)
backup_dir="/run/media/vincent/backup"
logfile="$backup_dir/archlinuxbackup.log"
backup_arch="$backup_dir/archlinux/"
exclude_file="/home/vincent/dotfiles/scripts/backup_ignore.txt"


if ! mountpoint -q $backup_dir ; then 
  echo "Mounting backup disk"
  udisksctl mount -b /dev/disk/by-label/backup
fi

echo "Backing up to $backup_arch"

# Option -a doesn't work with exfat because of permissions
#
# man says:
#   -a is equivalent to -rlptgoD
#
#   r: recursive
#   l: symlink
#   p: perms
#   t: time
#   g: groups
#   o: owner
#   D: devices and special files
#   v: verbose
#   u: update
#   h: humain-readable

rsync -avh \
  --delete \
  --delete-excluded \
  --exclude-from=$exclude_file \
  / $backup_arch

[ $? -eq 0 ] && echo "Successfully backed up on $date" > "$logfile"
