#!/bin/bash

file="/tmp/$(date -Is).png"

output=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused)' | jq -r '.name')

grim -o "$output" "$file"
wl-copy < "$file"

notify-send -t 3000 "Screenshot" $file
