#!/bin/bash

beg=`date -I -d "$(date +"%Y-%m-01") - 1 month"`
end=`date -I -d "$(date +"%Y-%m-01") - 1 day"`

echo -e "Period: \e[33m$beg..$end\e[39m\n"

echo "Balance:"

ledger bal \
  Liabilities:VAT Payable \
  Assets:VAT Deductible \
  -e $end

echo ""
echo "Details:"

ledger reg \
  Assets:VAT Deductible \
  Liabilities:VAT Payable \
  Income:Freelance \
  -b $beg -e $end

