#!/bin/bash

beg=$(date -I -d "$(date +"%Y-%m-01") - 3 month")
end=$(date -I -d "$(date +"%Y-%m-01") - 1 day")

echo -e "Period: \e[33m$beg..$end\e[39m\n"

echo "Balance:"

ledger bal \
  Income:Freelance \
  -b "$beg" -e "$end"

echo ""
echo "Details:"

ledger reg \
  Income:Freelance \
  -b "$beg" -e "$end"
