#!/bin/bash

if [ -z "$(pgrep -x wf-recorder)" ]; then
  file="/tmp/record.mp4"
  rm -f $file

  geom=$(slurp)

  if [ -z "$geom" ]; then
    exit
  fi

  wf-recorder -g "$geom" -f "$file" &

  # Notify waybar that it's recording
  while [ -z $(pgrep -x wf-recorder) ]; do sleep 0.1; done
  pkill -SIGRTMIN+8 waybar

else
  pkill -SIGINT wf-recorder

  # Notify waybar that it's no longer recording
  while [ ! -z $(pgrep -x wf-recorder) ]; do sleep 0.1; done
  pkill -SIGRTMIN+8 waybar
fi
