#!/bin/bash

set -eo pipefail

function cleanup {
  if [ ! -s "$file" ] ; then
    rm -rf "$file"
  fi
}

trap cleanup EXIT


now="$(date +%s)"
tpl="/tmp/scratchpad.$now.XXX.md"
file="$(mktemp "$tpl")"

cd /tmp
nvim "$file"
